# Generated by Django 5.0.4 on 2024-05-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
