# Generated by Django 5.0.4 on 2024-05-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaraunts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='reviews_count',
        ),
    ]
