# Generated by Django 5.0.4 on 2024-05-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaraunts', '0003_restaurant_reviews_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='reviews_count',
        ),
    ]
