# Generated by Django 5.0.4 on 2024-05-04 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaraunts', '0006_alter_reviews_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='photo',
        ),
        migrations.CreateModel(
            name='ReviewPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/reviews/')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_image', to='restaraunts.reviews')),
            ],
        ),
    ]
